name: Deploy Snowflake Objects

on:
  push:
    branches:
      - main

  workflow-dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: instaling snowflake
        run: pip install snowflake
      
      - name: instaling snowflake-cli-labs
        run: pip install snowflake-cli-labs

      - name: Deploy objects
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT}}
          SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME}}
          SNOWFLAKE_PWD: ${{ secrets.SNOWFLAKE_PWD}}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE}}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE}}

        run: |
          snow sql -q "ALTER GIT REPOSITORY GIT_INTEGRATION.DEPLOYMENT.SNOWFLAKE_PROD FETCH"  --temporary-connection --account $SNOWFLAKE_ACCOUNT --user $SNOWFLAKE_USERNAME --password SNOWFLAKE_PWD --role $SNOWFLAKE_ROLE --warehouse $SNOWFLAKE_WAREHOUSE 
          snow sql  -q"EXECUTE IMMEDIATE FROM  @GIT_INTEGRATION.DEPLOYMENT.SNOWFLAKE_PROD/branches/DEV/to_deploy_Snowflake_code/Snowflake Object Creatio.sql using (env => 'DEV' , schema_name => 'datamart')" --temporary-connection --account $SNOWFLAKE_ACCOUNT --user $SNOWFLAKE_USERNAME --password SNOWFLAKE_PWD --role $SNOWFLAKE_ROLE --warehouse $SNOWFLAKE_WAREHOUSE 