name: Deploy Snowflake Objects

on:
  push:
    branches:
      - main
      - QA
      - DEV
    paths:
      - 'to_deploy_Snowflake_code/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: instaling snowflake
        run: pip install snowflake
      
      - name: instaling snowflake-cli-labs
        run: pip install snowflake-cli-labs

      - name: Deploy objects
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_PWD: ${{ secrets.SNOWFLAKE_PWD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ github.ref == 'refs/heads/main'  && secrets.SNOWFLAKE_DATABASE_PROD || github.ref == 'refs/heads/QA'  && secrets.SNOWFLAKE_DATABASE_QA || github.ref == 'refs/heads/DEV'  && secrets.SNOWFLAKE_DATABASE_DEV  }}


        run: |
          for folder in snowflake_prod/to_deploy_Snowflake_code/*/; do
            echo "Processing folder $(basename $folder) ..."
            log_folder = logs/$(basename $folder)
            mkdir -p $log_folder
            for sqlfile in $folder/*; do
              snow sql -f $sqlfile --temporary-connection --account $SNOWFLAKE_ACCOUNT --user $SNOWFLAKE_USERNAME --password $SNOWFLAKE_PWD --role $SNOWFLAKE_ROLE --warehouse $SNOWFLAKE_WAREHOUSE --database $SNOWFLAKE_DATABASE > $log_folder/$(basename $sqlfile .sql).txt
            done
          done
