name: Deploy Snowflake Objects

on:
  push:
    branches:
      - main
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: instaling snowflake
        run: pip install snowflake
      
      - name: instaling snowflake-cli-labs
        run: pip install snowflake-cli-labs

      - name: Deploy objects
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_PWD: ${{ secrets.SNOWFLAKE_PWD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}


        run: |
          echo $SNOWFLAKE_ACCOUNT $SNOWFLAKE_USERNAME $SNOWFLAKE_PWD $SNOWFLAKE_ROLE $SNOWFLAKE_WAREHOUSE