name: Deploy Snowflake Objects

on:
  push:
    branches:
      - main
      - QA
      - DEV


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4


      - name: Set Environment Variable
        env: 
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_PWD: ${{ secrets.SNOWFLAKE_PWD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ github.ref == 'refs/headd/main' && secrets.SNOWFLAKE_DATABASE_PROD ||  github.ref == 'refs/headd/QA' && secrets.SNOWFLAKE_DATABASE_QA  ||  github.ref = 'refs/headd/DEV' && secrets.SNOWFLAKE_DATABASE_DEV}} 
                               

        run: |
          echo SNOWFLAKE_ACCOUNT: $SNOWFLAKE_ACCOUNT
          echo  SNOWFLAKE_USERNAME: $SNOWFLAKE_USERNAME
          echo  SNOWFLAKE_ROLE: $SNOWFLAKE_ROLE
          echo  SNOWFLAKE_WAREHOUSE: $SNOWFLAKE_WAREHOUSE
          echo  SNOWFLAKE_DATABASE: $SNOWFLAKE_DATABASE


          