name: Deploy Snowflake Objects

on:
  push:
    branches:
      -main

  workflow-dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: instaling snowflake
        run: pip install snowflake
      
      - name: instaling snowflake-cli-labs
        run: pip install snowflake-cli-labs

      - name: Deploy objects
        run: |
          snow sql -q "ALTER GIT REPOSITORY GIT_INTEGRATION.DEPLOYMENT.SNOWFLAKE_PROD FETCH"  --temporary-connection --account msbgaqj-pwb28963 --user Abhibangal --role ACCOUNTADMIN --warehouse COMPUTE_WH 
          snow sql  -q"EXECUTE IMMEDIATE FROM  @GIT_INTEGRATION.DEPLOYMENT.SNOWFLAKE_PROD/branches/DEV/to_deploy_Snowflake_code/Snowflake Object Creatio.sql using (env => 'DEV' , schema_name => 'datamart')" --temporary-connection --account msbgaqj-pwb28963 --user Abhibangal --role ACCOUNTADMIN --warehouse COMPUTE_WH 